apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replica set labels
  labels:
    purpose: taints-tolerations
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: taints-tolerations
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: taints-tolerations
        project: roboshop
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: ip-192-168-25-152.ec2.internal
      containers:
      - name: nginx
        image: nginx:latest
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effect: "NoSchedule"

        